ARG PROMETHEUS_OPERATOR_UPSTREAM_IMAGE=quay.io/prometheus-operator/prometheus-operator:v0.92.0
FROM ${PROMETHEUS_OPERATOR_UPSTREAM_IMAGE}

LABEL org.opencontainers.image.title="KDB Prometheus Operator"
LABEL org.opencontainers.image.source="quay.io/prometheus-operator/prometheus-operator"
