ARG PROMETHEUS_CONFIG_RELOADER_UPSTREAM_IMAGE=quay.io/prometheus-operator/prometheus-config-reloader:v0.92.0
FROM ${PROMETHEUS_CONFIG_RELOADER_UPSTREAM_IMAGE}

LABEL org.opencontainers.image.title="KDB Prometheus Config Reloader"
LABEL org.opencontainers.image.source="quay.io/prometheus-operator/prometheus-config-reloader"
