ARG ALERTMANAGER_UPSTREAM_IMAGE=quay.io/prometheus/alertmanager:v0.33.0
FROM ${ALERTMANAGER_UPSTREAM_IMAGE}

LABEL org.opencontainers.image.title="KDB Alertmanager"
LABEL org.opencontainers.image.source="quay.io/prometheus/alertmanager"
