ARG PROMETHEUS_UPSTREAM_IMAGE=quay.io/prometheus/prometheus:v3.12.0
FROM ${PROMETHEUS_UPSTREAM_IMAGE}

LABEL org.opencontainers.image.title="KDB Prometheus"
LABEL org.opencontainers.image.source="quay.io/prometheus/prometheus"
